### ISSUE TITLE
A lot of trigger conditions are wrong in the template for Zabbix 4.2

### ISSUE THREAD

**Issue by tonny1983** [hermanekt/Zabbix_wildfly_eap_jboss_monitoring#3]
There are many strange trigger conditions in in the template for Zabbix 4.2. For example, the expression of trigger named `90% Non-Heap Memory used on {HOST.NAME}` is `{Template JMX Wildlfy:jmx[&quot;java.lang:type=Memory&quot;,NonHeapMemoryUsage.used].last(0)}&lt;({Template JMX Wildlfy:jmx[&quot;java.lang:type=Memory&quot;,NonHeapMemoryUsage.max].last(0)}*0.9)` which means if used NonHeapMemory is **less than** 90% of max NonHeapMemory the trigger will be fired. Meanwhile, the expression of the same trigger in the template for Zabbix 4.0 is `{Template JMX Wildlfy:jmx[&quot;java.lang:type=Memory&quot;,NonHeapMemoryUsage.used].last(0)}&gt;({Template JMX Wildlfy:jmx[&quot;java.lang:type=Memory&quot;,NonHeapMemoryUsage.max].last(0)}*0.9)`  which should be correct. 

Is there any reason for reversed comparisons for Zabbix 4.2?

**Comment by hermanekt** [comment]
Hi Tonny,

i think i already fix in older version i recheck all version and after this i fix if find something:)

Thanks for info.

**Comment by hermanekt** [comment]
Hi Tonny,

again i thank you i found a lot of bugs duble triggers and wrong expressions. I delete template 4.2 template 4.0 is OK.

Tom

**Comment by hermanekt** [comment]
DONE

**Comment by tonny1983** [comment]
Thanks a lot for your great work @hermanekt . It really helps me a lot.
